### PR TITLE
fixes #84 - Update the ReadMe file 

### LINKED ISSUE #84: Update the ReadMe File

### PR DESCRIPTION
**Pull request by kasthurimenon**
Updated the ReadMe File. Will need one more update after adding screenshots.

### CODE REVIEW

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Comment by kasthurimenon** [comment]
Fixes #84. Updated the ReadMe File

**Review by adam-thibodeaux — APPROVED** [review]
great readme! thanks kas : )

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Review by janilya — APPROVED** [review]
Thanks for taking care of this!

**Pull request merged**
