### PR TITLE
fixes #43

### LINKED ISSUE #43: Update MongoDB account with samsa google account and not personal account

### PR DESCRIPTION
**Pull request by kasthurimenon**
- [x] created mongoDB account for saamsa gmail account
- [x] Added team members IP address's
- [x] Made changes to userModels file to accommodate the DB change
- [x] Verified that details are getting stored in new mongoDB 
Fixes #43

### CODE REVIEW

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Review by adam-thibodeaux — COMMENTED** [review]
edit: see below, forgot to change the type of comment to "request change"

**Review by adam-thibodeaux — CHANGES_REQUESTED** [review]
can you delete the index.js file? for some reason the index.ts compiled file ended up in this commit

**Comment by kasthurimenon** [comment]
> can you delete the index.js file? for some reason the index.ts compiled file ended up in this commit

> Done and pushed!

**Review by adam-thibodeaux — APPROVED** [review]
LGTM!

**Review by shamilahfaria — APPROVED** [review]
no issues to me!

**Pull request merged**
