### PR TITLE
Fixes #72 - error handling added 

### LINKED ISSUE #72: robust error handling in server

### PR DESCRIPTION
**Pull request by kasthurimenon**
Fixes #72 

- Added error handling to the following files
  1. kafkaController
  2. userController

- Cleaned up some console log statements.

### CODE REVIEW

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Comment by adam-thibodeaux** [comment]
Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>

**Comment by kasthurimenon** [comment]
-Added error handling to the following files
  -kafkaController
  -userController
-Cleaned up some console log statements.
- Fixes #72

**Review by adam-thibodeaux — APPROVED** [review]

**Review by janilya — APPROVED** [review]
Great job Kas! Fixes #72

**Comment by kasthurimenon** [comment]
Merging PR.

**Comment by kasthurimenon** [comment]
merging PR

**Pull request merged**
